name: 'build-test'

env:
  BUILD_TYPE: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.16.x'
        
    - name: Use cmake
      run: cmake --version
      
    - uses: actions/checkout@v2
      name: Check out code
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: hyiik09/assignment3
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
