name: test C

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: |
          brew install graphviz ninja doxygen
    - name: configure
      run: cmake -G Ninja -B ./build -S .

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: actions/checkout@v2
      name: Check out code
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: hyiik09/assignment
        registry: docker.io
        
    - name: Script
      run: |
        docker build -t app .
        docker tag app hyiik09/assignment
        docker push hyiik09/assignment

      
   # - name: Docker Build and Push C
   # - uses: mr-smithers-excellent/docker-build-push@v5
   #   with:
   #     image: docker-hub-repo/image-name
   #     registry: docker.io
   #     username: ${{ secrets.DOCKER_USERNAME }}
   #     password: ${{ secrets.DOCKER_PASSWORD }}
   
   
      
